const questions = [
  {
    Qid: 1,
    category: "Technical Skills and Problem-Solving",
    question: "Can you describe a project you've built (either personal or group)? What part did you enjoy working on the most?",
    type: 'text',
    video:"/videos/q1.mp4",
  },
  {
    Qid: 2,
    category: "Technical Skills and Problem-Solving",
    question: "Tell us about a challenging bug or issue you encountered during this project. How did you approach solving it?",
    type: 'text',
    video:"",
  },
  {
    Qid: 3,
    category: "Technical Skills and Problem-Solving",
    question: "Rate your familiarity from 1 (Beginner) to 5 (Advanced).",
    type: 'rating',
    options: [1, 2, 3, 4, 5],
    video:"",
  },
  {
    Qid: 4,
    category: "Learning and Adaptability",
    question: "How often do you dedicate time to learning new coding skills?",
    type: 'text',
    video:"",
  },
  {
    Qid: 5,
    category: "Learning and Adaptability",
    question: "What is one new technology or concept you've recently taught yourself?",
    type: 'text',
    video:"",
  },
  {
    Qid: 6,
    category: "Learning and Adaptability",
    question: "When faced with a concept you don’t understand, what steps do you take to figure it out?",
    type: 'text',
    video:"",
  },
  {
    Qid: 7,
    category: "Work Ethic, Dedication & Teamwork",
    question: "When faced with a tight deadline, how would you describe your typical reaction?",
    type: 'text',
    video:"",
  },
  {
    Qid: 8,
    category: "Work Ethic, Dedication & Teamwork",
    question: "Share an instance from your recent projects where you put in extra effort to get things done. What was your main motivation?",
    type: 'text',
    video:"",
  },
  {
    Qid: 9,
    category: "Work Ethic, Dedication & Teamwork",
    question: "What qualities do you think are important for a successful developer?",
    type: 'text',
    video:"",
  },
  {
    Qid: 10,
    category: "Goals and Future Plans",
    question: "In one word, what is your biggest career goal?",
    type: 'text',
    video:"",
  },
  {
    Qid: 11,
    category: "Goals and Future Plans",
    question: "What is your plan after the internship & Why?",
    type: 'text',
    video:"",
  },
  {
    Qid: 12,
    category: "Goals and Future Plans",
    question: "Why did you choose to pursue an internship, and what do you hope to gain from it?",
    type: 'text',
    video:"",
  },
];

export default questions;
